Django/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('shop/', include('shop.urls')),
    path('myauth/', include('myauth.urls')),
    path('myapiapp/', include('myapiapp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

Django/myauth/urls.py
from django.urls import path, re_path
from myauth.views import *

app_name = 'myauth'
urlpatterns = [
    #path('', login_view, name='login'),
    path('', BBLoginView.as_view(), name='login'),
    path('logout/', BBLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterVieww.as_view(), name='register'),
]

Django/shop/urls.py
from django.urls import path, re_path
from shop.views import *

app_name = 'shop'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    #re_path(r'^about', about, name='about'),  # url для def
    path('about/', CourseCreate.as_view(), name='about'),
    re_path(r'product/(?P<id_producte>\d+)/(?P<producte>\D+)/', product),
    path('groups/', groups_list, name='groups-list'),
    path('products/', ProductsList.as_view(), name='products-list'),
    path('order/', OrderList.as_view(), name='order-list'),
    # path('<int:id>', single_course, name='single'),
    path('<int:pk>', SingleCourse.as_view(), name='single'),
    path('other-form/', other_form, name='other-form'),
    # path('<int:id>//', delete, name='delete'), # url для def
    path('<int:pk>//', CourseDelete.as_view(), name='delete'),
    # path('<int:id>/', edit, name=' edit'), # url для def
    path('<int:pk>/', CourseUpdate.as_view(), name=' edit'),  # url для class
    path('<int:pk>/!', ProductDetailsView.as_view(), name='product-detail')

]

Django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
            курс по верстке
        {% endblock %}
    </title>
    <style>
        html {
            margin: 0;
        }

        * {
            font-family: Arial;
        }

        body {
            text-align: center;
            background-color: silver;
            margin: 0;
        }

        h1 {
            color: crimson;
        }

        h2 {
            color: #3A7734;
        }

        th {
            color: darkblue;
        }

        td {
            color: maroon;
            font-weight: bold;
        }

        footer {

            padding: 40px;
        }

        header {
            height: 70px;
            padding: 0 40px;
        }

        header > div {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .fixed-container {
            max-width: 1000px;
            height: 100%;
            margin-left: auto;
            margin-right: auto;
            background-color: lightblue;
        }

        .eugene {
            color: blue;
        }

        .natalia {
            color: #3A7734;
        }

        section {
            padding: 40px;
        }

        .services {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;

        }

        .services > div {
            width: 200px;

        }

        .services img {
            width: 150px;
        }

        .first-block {
            height: 300px;
        }

        .first-block > div {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: flex-start;
            background-image: url("{% static 'eugene.jpg' %}");
            background-size: contain;
            background-repeat: no-repeat;
            background-position: right center;
        }

        .light-button {
            border: 1px solid black;
            background-color: transparent;
        }

        .darck-button {
            background-color: blue;
            border: 1px solid blue;
            color: white;
        }

        button {
            padding: 10px 30px;
            cursor: pointer;
            border-radius: 5px;
        }

        .popup-container {
            background-color: #000000b3;
            position: fixed;
            width: 100%;
            height: 100%;
            display: none;
            justify-content: center;
            align-items: center;
        }

        .popup {
            background-color: white;
            width: 300px;
            height: 300px;
            padding: 30px;
            border-radius: 5px;
        }

    </style>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var container = document.querySelector('.popup-container');
            var popupButtons = document.querySelectorAll('.open-popup');
            for (let i=0; i<popupButtons.length; i++){
                popupButtons[i].addEventListener('click', function (){
                    container.style.display = 'flex';
                })
            }
        });
    </script>
</head>
<header>
    <div class="popup-container">
        <form class="popup">

        </form>
    </div>

    <div class="fixed-container">
        <div>
            <a href="#">Послуги</a>
            <a href="#">Ввід товару</a>
        </div>
        <div>
            <span>+380502278358</span>
            <button class="light-button open-popup">Заказать звонок</button>
        </div>
    </div>
</header>
<body>

{% block body %}
    <h2>Base course</h2>
{% endblock %}

{% block content %}
{% endblock %}
<section class="first-block">
    <div class="fixed-container">
        <h1 class="eugene">Eugene Nearonov </h1>
        <p>Fronted розробник</p>
        <button class="darck-button open-popup">Узнати більше</button>
    </div>
</section>

<section>
    <div class="fixed-container">
        <h2 class="natalia">Що я роблю</h2>
        <div class="services">
            <div>
                <img src="{% static 'java.png' %}" alt="">
                Розробка і програмування на мові java.
            </div>
            <div>
                <img src="{% static 'go-programming-language-logo-black-background-2M8NA9T.jpg' %}" alt="">
                Розробка і програмування на мові GO.
            </div>
            <div>
                <img src="{% static 'Без названия.png' %}" alt="">
                Аналіз даних
            </div>
            <div>
                <img src="{% static 'ruby.jfif' %}" alt="">
                Розробка і програмування на мові ruby.
            </div>
        </div>
        <button class="open-popup">Узнати вартість</button>
    </div>
</section>

<section>
    <div class="fixed-container">
        <h2 class="natalia">Приклад роботи</h2>
    </div>
</section>
</body>


<footer>
    <div class="fixed-container">
        <div>
            {% now 'H:i' %}
        </div>
        <div>
            {% now 'l'  as current_weekday %}
            To day is {{ current_weekday }}
        </div>
        <a href="#">Послуги</a>
        <a href="#">Ввід товару</a>
    </div>
</footer>
</html>

Django/templates/base_2.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        a:hover{
            color: green;
        }
         td{
            color: maroon;
            font-weight: bold;
        }
        .light-button {
            position: fixed;
            text-decoration: none;
            color: red;
            display: flex;
            align-items: center;
            justify-content: center;
            right: 10px;
            top: 10px;
            background-color: limegreen;
            padding: 5px;
            width: 80px;
            height: 20px;
            border-radius: 5px;
         }
        .open-popup{
            position: absolute;
            text-decoration: none;
            color: red;
            display: flex;
            align-items: center;
            justify-content: center;
            right: 10px;
            padding: 10px;
            width: 80px;
            height: 20px;
        }
    </style>
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>

<body>
    <nav class=" navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <a href={% url "shop:index" %}  class="navbar-grand">Courses Shop</a>
        </div>
        <div class="container-fluid">
            <a href={% url "shop:about" %}  class="navbar-grand">Ввод курсів </a>
        </div>
        <div class="container-fluid">
             <a class="navbar-grand " href={% url "myauth:login"%}>
             <button class="light-button open-popup" >Увійти</button></a>
        </div>
        {% if user.is_authenticated %}
            <div class="container-fluid">
                 <a class="navbar-grand " href={% url "myauth:logout" %}>
                 <button class="open-popup" >Вийти</button></a>
            </div>
        {% endif %}
    </nav>

    <main class="container">  {#    отступ зліва і праворуч#}
    {% block content %}
    {% endblock %}
    </main>
</body>




{% block footer %}

    <div>
    {% now 'H:i' %}
  </div>
  <div>
    {% now 'l'  as current_weekday%}
    To day is {{ current_weekday }}
   </div>

{% endblock %}
</html>

Django/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Course</title>
</head>
<body>
    <h1>Ви на головній сторінці</h1>
    <h2>templates/index.html</h2>

</body>
</html>