Django/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('shop/', include('shop.urls')),
    path('myauth/', include('myauth.urls')),
    path('myapiapp/', include('myapiapp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

Django/shop/urls.py
from django.urls import path, re_path
from shop.views import *

app_name = 'shop'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    #re_path(r'^about', about, name='about'),  # url для def
    path('about/', CourseCreate.as_view(), name='about'),
    re_path(r'product/(?P<id_producte>\d+)/(?P<producte>\D+)/', product),
    path('groups/', groups_list, name='groups-list'),
    path('products/', ProductsList.as_view(), name='products-list'),
    path('order/', OrderList.as_view(), name='order-list'),
    # path('<int:id>', single_course, name='single'),
    path('<int:pk>', SingleCourse.as_view(), name='single'),
    path('other-form/', other_form, name='other-form'),
    # path('<int:id>//', delete, name='delete'), # url для def
    path('<int:pk>//', CourseDelete.as_view(), name='delete'),
    # path('<int:id>/', edit, name=' edit'), # url для def
    path('<int:pk>/', CourseUpdate.as_view(), name=' edit'),  # url для class
    path('<int:pk>/!', ProductDetailsView.as_view(), name='product-detail')

]

Django/shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone



# from myauth.models import AdvUser



class Category(models.Model):
    title = models.CharField(max_length=255)
    create_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.title}"


class Course(models.Model):
    title = models.CharField(max_length=255)
    price = models.FloatField(blank=True, null=True)
    students_qty = models.IntegerField(blank=True, null=True)
    reviews_qty = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    create_at = models.DateTimeField(default=timezone.now)
    foto = models.ImageField(upload_to='images',
                             help_text="Введіть зображення курсів",
                             verbose_name="Зображення курсів",
                             blank=True)

    # Курси розтошувати в алфавитном порядку
    class Meta:
        ordering = ['title']
        verbose_name = 'Назва курсів'

    def __str__(self):
        return f"{self.title}"


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"


class Order(models.Model):
    delivery_address = models.TextField(null=False, blank=True)
    promo_code = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

Django/shop/forms.py
from django import forms
from .models import Course, Product


class CourseForm(forms.ModelForm):
    title = forms.CharField(label="назва курса",
                            max_length=30,
                            initial="Введіть назву курса",
                            )

    # category = forms.ChoiceField(label="категорія курсів",
    #                              choices=((1, 'Programming'),
    #                                       (2, 'Data science'),
    #                                       (3, 'Web designer')))

    class Meta:
        model = Course
        fields = ['title', 'category', 'price', 'foto']


class CourseEdit(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'price']
        labels = {'title': "Змінити назву курса", 'price': 'Ціна'}


class ProductsCreate(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'discount']
        labels = {'name': "Ввести назву подукта",
                  'price': 'Ввести ціну',
                  'discount': 'знижка'
                  }

Django/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest, Http404  # для анатаціі типів request
from django.contrib.auth.models import Group
from .models import Course, Product, Order
from .forms import CourseForm, CourseEdit, ProductsCreate
from django.views import View
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic import TemplateView, ListView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
import requests


# def index(request: HttpRequest):
#     courses = Course.objects.all()
#     return render(request, "shop/courses.html", {'courses': courses})


# class Index(TemplateView):
#     template_name = 'shop/courses.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['courses'] = Course.objects.all()
#         return context

class Index(ListView):
    template_name = 'shop/courses.html'
    model = Course
    context_object_name = 'courses'


def other_form(request: HttpRequest):
    courses = Course.objects.all()
    return render(request, "shop/other_form.html", {'courses': courses})


# Ввід курсів при допомозі класа CreateView
class CourseCreate(CreateView):
    model = Course
    fields = ['title', 'category', 'price', 'students_qty', 'reviews_qty', 'foto']
   # form_class = CourseForm
    success_url = reverse_lazy("shop:index")


# Ввід курсів при допомозі функціі
# def about(request: HttpRequest):
#     if request.method == 'POST':
#         my_form = CourseForm(request.POST)
#         if my_form.is_valid():
#             my_form.save()
#         return redirect('shop:index')
#
#     my_form = CourseForm()
#     context = {'form': my_form}
#     return render(request, 'shop/course_form.html', context)


def product(request, id_producte, producte):
    output = "<h2>Продукт:№{0}</h2> <h3>Імя продукта : {1}</h3>".format(id_producte, producte)
    return HttpResponse(output)


def groups_list(request: HttpRequest):
    groups = Group.objects.prefetch_related('permissions').all()
    cotext = {
        'groups': groups
    }
    return render(request, "shop/groups-list.html", cotext)


class ProductsList(View):
    def get(self, request: HttpRequest):
        products = Product.objects.all()
        form = ProductsCreate()
        context = {
            'products': products,
            'form': form
        }
        return render(request, "shop/products-list.html", context)

    def post(self, request: HttpRequest):
        form = ProductsCreate(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


# class ProductDetailsView(View):
#     def get(self, request: HttpRequest, pk: int):
#         # product = Product.objects.get(pk=pk)
#         product = get_object_or_404(Product, pk=pk)
#         return render(request, "shop/product-details.html", {"product": product})
class ProductDetailsView(DetailView):
    template_name = 'shop/product-details.html'
    model = Product
    context_object_name = 'product'


# Відображення продуктів при допомозі функціі
# def products_list(request: HttpRequest):
#     products = Product.objects.all()
#     context = {
#         'products': products
#     }
#     return render(request, "shop/products-list.html", context)


# def order_list(request: HttpRequest):
#     orders = Order.objects.select_related('user').prefetch_related('products').all()
#     context = {
#         'orders': orders
#     }
#     return render(request, "shop/order-list.html", context)


class OrderList(ListView):
    template_name = 'shop/order-list.html'
    queryset = (
        Order.objects.select_related('user').prefetch_related('products')
    )
    context_object_name = 'orders'


# def single_course(request: HttpRequest, id):
#     try:
#         course = Course.objects.get(pk=id)
#         return render(request, "shop/single_course.html", {"course": course})
#     except Course.DoesNotExist:
#         raise Http404()


class SingleCourse(DetailView):
    template_name = 'shop/single_course.html'
    model = Course
    context_object_name = 'course'


def delete(request: HttpRequest, id):
    course = Course.objects.get(pk=id)
    course.delete()
    return redirect('shop:index')


class CourseDelete(DeleteView):
    model = Course
    success_url = reverse_lazy("shop:index")


# def edit(request: HttpRequest, id):
#     course = Course.objects.get(id=id)
#     if request.method == 'POST':
#         course.title = request.POST.get('title')
#         # course.category = request.POST.get('category')
#         course.price = request.POST.get('price')
#         course.save()
#         return redirect('shop:index')
#
#     else:
#         courses = CourseEdit()
#         context = {'form': courses}
#         return render(request, 'shop/update_course.html', context)
#

# редогування на основі класа UpdateView
class CourseUpdate(UpdateView):
    model = Course
    fields = ['title', 'price', 'foto']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('shop:index')

Django/templates/shop/course_confirm_delete.html
{% extends "base_2.html" %}
{% block content %}
    <h1>Видалення курса</h1>
    <h2>Ви впевноні, що хочите видалити курс: {{ course }}</h2>
    <form action="" method="POST">
        {% csrf_token %}

        <input type="submit" action="" value="Видалити"/>
    </form>
{% endblock %}

Django/templates/shop/course_form.html
{% extends 'base_2.html' %}

{% block title %}
    Ввод курсів
{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>form</title>
    <h1>Ввод курсів</h1>
</head>
<body>
<div class="container-fluid my-2 border border-3">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_p}}

        </table>

        <input type="submit" value="Відправити">
    </form>
</div>
</body>
{% endblock %}

Django/templates/shop/course_update_form.html
{% extends "base_2.html" %}
 {% block title %}
     update course
 {% endblock %}
{% block content %}
    <h1>Update</h1>
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
<tаЫе>

{{ form.as_p }}

</tаЫе>
<input type="submit" value="Сохранить" />
</form>
{% endblock %}

Django/templates/shop/courses.html
{% extends 'base_2.html' %}

{% block title %}
    All courses
{% endblock %}

{% block content %}

{% if courses %}
<table class="table mt-5 table-bordered table-striped  table-hover" >
{#       width='550' border='2' bordercolor='black'#}
{#       cellspacing='1' cellpadding='8' align="center" >#}
    <thead class="table-dark">
        <tr>
            <th>Курси</th>
            <th>Фото</th>
            <th>Категорія</th>
            <th>Вартість</th>
            <th>Кількість судентів</th>
            <th>Kількість відгуків</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>

    {% for course in courses %}
        <tr>
            <td><a href={% url "shop:single" course.id %}>{{course.title}}</a></td>
            {% if course.foto %}
                <td><img class="card-img-top" src="{{ course.foto.url }}" style ="max-height: 70px;" alt="foto" ></td>
            {% else %}
                <td></td>
            {% endif %}
            <td>{{course.category}}</td>
            <td>{{course.price}}</td>
            <td>{{course.students_qty}}</td>
            <td>{{course.reviews_qty}}</td>
            <td><a href={% url "shop: edit" course.id %}><button class="btn btn-primary">Редогувати</button></a></td>
            <td><a href={% url "shop:delete" course.id%}><button  class="btn btn-danger" >Видалити</button></a></td>
        </tr>
        </lo>
    {% endfor %}
    </tbody>

</table>
{% else %}
Даних немає.
{% endif %}

{% endblock %}

Django/templates/shop/groups-list.html
{% extends 'base.html' %}

 {% block title %}
     Groups list
 {% endblock %}

{% block content %}
    <h1>Groups:</h1>
    <div>
    {% if not groups %}
        <h2>
            Групи відсутні.
        </h2>
    {% else %}
        <ul>
             {% for group in groups %}
            <li>
                <div>{{ group.name }}</div>
                <ul>
                    {% for permission in group.permissions.all %}
                    <li>{{ permission.name }}
                        ( <code>{{ permission.codename }}</code>)
                    </li>
                     {% endfor %}
                </ul>

            </li>
    {% endfor %}
        </ul>
    {% endif %}

    </div>
{% endblock %}

Django/templates/shop/order-list.html
{% extends 'base.html' %}

 {% block title %}
     Order list
 {% endblock %}

{% block body %}
    <h1>Order:</h1>
    <div>
    {% if not orders %}
        <h2>
            Закази відсутні.
        </h2>
    {% else %}
        <ul>
{#             {% for product in products %}#}
{#            <li>#}
{#                <div>Name:{{ product.name }}</div>#}
{#                 <div>Price:{{ product.price }}</div>#}
{#                <div>discount:{% firstof product.discount 'no discount' %}</div>#}
{#             {% endfor %}#}
                <table width='550' border='2' bordercolor='black'
                  cellspacing='1' cellpadding='8' align="center"
                 BGCOLOR="#87ceeb" >
        <thead>
            <tr >
                <th >Адреса доставки</th>
                <th BGCOLOR="#ff7f50">Промо код</th>
                <th BGCOLOR="#7cfc00">Час замовлення</th>
                <th>Покупець</th>
                <th BGCOLOR="#fff8dc">Товар</th>
                <th >Ціна</th>
                <th BGCOLOR="#CCCCCC">Купити товар</th>

            </tr>
            <tbody>

                {% for  order in orders %}
                    {% for product in order.products.all %}
                    <tr>
                        <td>{{order.delivery_address}}</td>
                        <td BGCOLOR="#ff7f50">{{order.promo_code}}</td>
                        <td BGCOLOR="#7cfc00">{{order.created_at}}</td>
                        <td>{% firstof order.user.first_name order.user.username %}</td>
                        <td BGCOLOR="#fff8dc">{{ product.name }}</td>
                        <td>{{ product.price }}</td>
                        <td BGCOLOR="#CCCCCC"><button>Купити</td>
                    </tr>
                    {% endfor %}
                {% endfor %}

            </tbody>
        </thead>
</table>
        </ul>

    {% endif %}

    </div>

{% endblock %}

Django/templates/shop/other_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>форма з відео-курса</title>
    <link rel="stylesheet" type="text/css" href="../../static/styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>

<body class="p-3 mb-2 bg-info text-dark"">
    <form class="reg-form" >
        <h1>Реєстрація на конференцію</h1>
        <div class="mb-3">
            <label for="name" class="form-label">
                Призвище Ім'я Побатькові
            </label>
            <input class="reg-form_input form-control" type="text" name="name" id="name">
        </div>
        <div class="mb-3">
            <label for="email"class="form-label">
                E-mail:
            </label>
            <input class="reg-form_input form-control" type="email" name="email" id="email">
        </div>
        <div class="mb-3">
            <label class="form-label">
                Стать
            </label>
            <div >
               <label>
                   <input class="form-check-input" type="radio" name="sex" value="male"> чоловічий
                   <input class="form-check-input" type="radio" name="sex" value="female"> жіночий
               </label>
                </div>
        </div>
        <div class="mb-3">
            <label class="form-label">
                Переважний час виступу:
            </label>
            <div >
                <label>
                    <input class="form-check-input" type="checkbox" name="time_morning" value="1">ранок
                </label>
                <label>
                     <input class="form-check-input" type="checkbox" name="time_afternoon" value="1">день
                </label>
                <label>
                    <input class="form-check-input" type="checkbox" name="time_evening" value="1">вечір
                </label>
            </div>
        </div>
        <div class="mb-3">
            <label class="form-label">Сєкціі</label>
            <select name="section" class="form-select">
                <option value="frontend">Frontend</option>
                <option value="backend">Backend</option>
                <option value="management">Management</option>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Тема і тезиси виступу</label>
            <textarea name="info" class="form-control"></textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">Презентація</label>
            <input type="file" class="form-control"  name="presentation">
        </div>
        <div class="mb-3">
            <input type="reset" class="btn btn-danger" value="Сброс">
            <input type="submit" class="btn btn-success" value="Відправити">
        </div>

    </form>

</body>
</html>

Django/templates/shop/product-details.html
{% block title %}
    Product details
{% endblock %}


{% block content %}
    <h1>Product : <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Discount :<em>{{ product.discount }}%</em></div>
    </div>
{% endblock %}

Django/templates/shop/products-list.html
{% extends 'base.html' %}

{% block title %}
    Products list
{% endblock %}


{% block content %}
    <style>
        .price-list {
            width: 550px;
            border: 1px solid black;
            align-self: center;
            margin: auto;
        }

        .price-list th, .price-list td {
            border: 1px solid black;
            padding: 5px;
        }

    </style>
    <h1>Create products:</h1>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <h1>Products:</h1>
    <div>
        {% if not products %}
            <h2>
                Прдукти відсутні.
            </h2>
        {% else %}
            <ul>
                {#             {% for product in products %}#}
                {#            <li>#}
                {#                <div>Name:{{ product.name }}</div>#}
                {#                 <div>Price:{{ product.price }}</div>#}
                {#                <div>discount:{% firstof product.discount 'no discount' %}</div>#}
                {#             {% endfor %}#}
                <table class="price-list">
                    <thead>
                    <tr>
                        <th bgcolor="#ffe4e1">Ім я</th>
                        <th BGCOLOR="#ff7f50">Ціна</th>
                        <th BGCOLOR="#7cfc00">знижка</th>
                        <th bgcolor="#deb887">Час додавання</th>
                        <th BGCOLOR="#CCCCCC">Купити товар</th>

                    </tr>
                    <tbody>

                    {% for product in products %}
                        <tr>
                            <td bgcolor="#ffe4e1"><a
                                    href="{% url "shop:product-detail" pk=product.pk %}"> {{ product.name }}</a></td>
                            <td BGCOLOR="#ff7f50">{{ product.price }}</td>
                            <td BGCOLOR="#7cfc00">{% firstof product.discount 'no discount' %} %</td>
                            <td bgcolor="#deb887">{{ product.created_at }}</td>
                            <td BGCOLOR="#CCCCCC">
                                <button>Купити
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                    <thead/>
                </table>

            </ul>

        {% endif %}

    </div>
{% endblock %}

Django/templates/shop/single_course.html
{% extends 'base_2.html' %}

{% block title %}
     {{course.title}}
{% endblock %}

{% block content %}
    <h1 class="mt-5">{{course.title}}</h1>
    <h2>{{course.category}}</h2>
    <p>Ціна:{{course.price}} $</p>
    <button class="btn btn-primary">Buy</button>
{% endblock %}

Django/templates/shop/update_course.html
{% extends 'base_2.html' %}

{% block title %}
    Редогування курсів
{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>form</title>
    <h1>Редогування</h1>
</head>
<body>
<div class="container-fluid my-2 border border-3">
    <form  method="POST">
        {% csrf_token %}
        <table>
            {{form.as_p}}
{#               <lаЬеl>Змінити назву</lаЬеl><br>#}
{#               <input type="text" title="title" value="{{form.title}}" /><br>#}
{#               <input type="text" title="title" value="{{form.price}}" /><br>#}


        </table>

        <input type="submit" value="Зберігти">
    </form>
</div>
</body>
{% endblock %}